spring:
  application:
    name: java-dividend-api

  datasource:
    url: jdbc:postgresql://localhost:5432/dividend_agent
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080